project_id = "opzsrqdvotozawuqpapo"

[functions.generate-ad]
verify_jwt = false

[functions.generate-product-images]
verify_jwt = false

[functions.parse-bank-statement]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
